- name: Install OSS-CAD-suite
  unarchive:
    src:  https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2022-10-04/oss-cad-suite-linux-x64-20221004.tgz
    dest: /opt
    remote_src: yes
